import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Links = () => {
  return (
    <>
      <p>Links</p>
    </>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <body className={inter.className} h-screen max-h-screen min-h-screen>
        <Links />
        <>
        {children}
        </>
      </body>
    </html>
  )
}
